# **Module 1: Programming Fundamentals for Machine Learning**

### **Prepared by**: Dr. Hum Nath Bhandari, Department of Mathematics, RWU

### **Course**: MATH 355/COMSC 415-Machine Learning 

### **Notebook 4**: Pandas Tutorial




### **Overview**

In this notebook we discuss about important external library in Python, called **Pandas**. Pandas has two core data structures, called **Series** and **DataFrame**. This library helps in reading, organizing, and manipulating data.


### **Learning Objectives**
- Importing Pandas library
- Creating Series and Dataframes
- Organizing data using Pandas DataFrame.
- Data filtering, reshaping, resizing.




## Pandas library

Pandas is an external library written for the Python programming language for data manipulation and analysis. In particular, it offers data structures and operations for manipulating numerical tables and time series (soruce: Wiki).


There are two important data structures in Pandas, called **Series** and **DataFrame**.

- **Series**: Series is a one-dimensional labeled array capable of holding any Python data type (integers, strings, floating point numbers, etc.). The axis labels are collectively referred to as the index.

- **DataFrame**: DataFrame is a two-dimensional, size-mutable, potentially heterogeneous tabular data structure. It is a primary Pandas data structure.This data structure also contains labeled axes (rows and columns). Can be thought of as a dict-like container for Series objects. 



### Review of Random Number Generators: 
https://numpy.org/doc/stable/reference/random/generated/numpy.random.RandomState.rand.html


In [ ]:
import numpy as np

In [ ]:
np.random.rand(3, 4)

array([[0.29877909, 0.24214849, 0.91005267, 0.18179702],
       [0.63173778, 0.40379412, 0.48367421, 0.52147531],
       [0.53130084, 0.54627819, 0.32602482, 0.61172066]])

In [ ]:
np.random.randn(3,4)

array([[-0.47855834,  0.90252054, -0.46923095,  1.06902391],
       [ 0.65404993,  0.09502178,  1.22658505, -1.0593189 ],
       [ 1.50813468, -0.8462362 ,  1.00274048, -1.34819102]])

In [ ]:
mu = 4
std = 3
mu + std*np.random.randn(3,4)

array([[ 1.88394894,  3.05280061,  4.18801846,  4.24255661],
       [ 3.88686965,  8.20050111,  1.64965703,  2.17842245],
       [ 4.27061234, 10.01138767,  5.75608136,  2.04872156]])

In [ ]:
import pandas as pd

In [ ]:
A = pd.Series( [3,4,5, True, 0.8,"USA"] )
A

0       3
1       4
2       5
3    True
4     0.8
5     USA
dtype: object

In [ ]:
import numpy as np

B= pd.Series(np.arange(6))
B

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [ ]:
df = pd.DataFrame(
    
     {
      "A" :  pd.Series([3,4,5, True, 0.8,"USA"]),
      "B":   pd.Series(np.arange(6)),
      "C":   np.random.rand(6)
    
   }

)

df

,A,B,C
0,3,0,0.246500
1,4,1,0.608165
2,5,2,0.396682
3,True,3,0.452941
4,0.8,4,0.267691
5,USA,5,0.836146


### **Basic Pandas Tutorials**

There is a short Pandas documentation which provides a basic idea about Pandas and its functionality. Please go to the following link.

[10 minutes to pandas](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html)

